--How many users were active on a given day (they made a deposit or withdrawal)

SELECT COUNT(DISTINCT USER_ID)
FROM MDM_DEV.MDM_SCHEMA.USER_ACTIVITIES_FACT UAF
LEFT JOIN MDM_DEV.MDM_SCHEMA.EVENT_NAME_DIM E ON E.ID = UAF.EVENT_NAME_ID
WHERE EVENT_NAME IN ('deposit', 'withdrawal') and date(event_timestamp) = '2020-02-10';

--Identify users haven't made a deposit
WITH dep as (
    SELECT USER_ID
    FROM MDM_DEV.MDM_SCHEMA.USER_ACTIVITIES_FACT UAF
    JOIN MDM_DEV.MDM_SCHEMA.EVENT_NAME_DIM E ON E.ID = UAF.EVENT_NAME_ID
    WHERE EVENT_NAME = 'deposit'
    GROUP BY 1)
SELECT USER_ID
FROM MDM_DEV.MDM_SCHEMA.USERS_DIM
MINUS
SELECT USER_ID
FROM dep;

--Identify on a given day which users have made more than 5 deposits historically

SELECT USER_ID, COUNT(event_name_id)
FROM MDM_DEV.MDM_SCHEMA.USER_ACTIVITIES_FACT UAF
JOIN MDM_DEV.MDM_SCHEMA.EVENT_NAME_DIM E ON E.ID = UAF.EVENT_NAME_ID
WHERE DATE(EVENT_TIMESTAMP) <= '2021-10-12'
GROUP BY 1 HAVING COUNT(event_name_id) > 5
ORDER BY 2 DESC;

--When was the last time a user made a login

SELECT USER_ID, MAX(EVENT_TIMESTAMP) LAST_LOGIN
FROM MDM_DEV.MDM_SCHEMA.USER_ACTIVITIES_FACT UAF
JOIN MDM_DEV.MDM_SCHEMA.EVENT_NAME_DIM E ON E.ID = UAF.EVENT_NAME_ID 
WHERE EVENT_NAME = 'login'
GROUP BY 1
ORDER BY 2 DESC;

--How many times a user has made a login between two dates

SELECT USER_ID, COUNT(EVENT_TIMESTAMP) LOGINS
FROM MDM_DEV.MDM_SCHEMA.USER_ACTIVITIES_FACT UAF
JOIN MDM_DEV.MDM_SCHEMA.EVENT_NAME_DIM E ON E.ID = UAF.EVENT_NAME_ID 
WHERE EVENT_NAME = 'login' AND DATE(EVENT_TIMESTAMP) BETWEEN '2020-01-01' AND '2020-12-31'
GROUP BY 1
ORDER BY 2 DESC;

--Number of unique currencies deposited on a given day
SELECT CURRENCY_NAME
FROM MDM_DEV.MDM_SCHEMA.USER_ACTIVITIES_FACT UAF
JOIN MDM_DEV.MDM_SCHEMA.EVENT_NAME_DIM E ON E.ID = UAF.EVENT_NAME_ID
JOIN MDM_DEV.MDM_SCHEMA.CURRENCY_DIM C ON C.ID = UAF.CURRENCY_ID
WHERE DATE(EVENT_TIMESTAMP) = '2020-10-12' AND EVENT_NAME = 'deposit'
GROUP BY 1;

-- Number of unique currencies withdrew on a given day
SELECT CURRENCY_NAME
FROM MDM_DEV.MDM_SCHEMA.USER_ACTIVITIES_FACT UAF
JOIN MDM_DEV.MDM_SCHEMA.EVENT_NAME_DIM E ON E.ID = UAF.EVENT_NAME_ID
JOIN MDM_DEV.MDM_SCHEMA.CURRENCY_DIM C ON C.ID = UAF.CURRENCY_ID
WHERE DATE(EVENT_TIMESTAMP) = '2020-10-12' AND EVENT_NAME = 'withdrawal'
GROUP BY 1;

--Total amount deposited of a given currency on a given day
SELECT CURRENCY_NAME, SUM(AMOUNT)
FROM MDM_DEV.MDM_SCHEMA.USER_ACTIVITIES_FACT UAF
JOIN MDM_DEV.MDM_SCHEMA.EVENT_NAME_DIM E ON E.ID = UAF.EVENT_NAME_ID
JOIN MDM_DEV.MDM_SCHEMA.CURRENCY_DIM C ON C.ID = UAF.CURRENCY_ID
WHERE DATE(EVENT_TIMESTAMP) = '2020-10-12' AND EVENT_NAME = 'deposit'
GROUP BY 1
ORDER BY 2 DESC;